### PR TITLE
Keep comments above a key-value pair as is

### LINKED ISSUE #11: Keep comments above a key-value pair as is
I tried out your library and it is really helpful. Thank you for your contribution.

Question: Do you think it is worthwhile to add an option to preserve (multi-line) comments that precede a key-value pair?

Example (from a pyproject.toml in one of my projects):

```toml
[tool.poetry.dependencies]
click = "^7.1.2"
coverage = {extras = ["toml"], optional = true, version = "^5.1"}
pytest = {optional = true, version = "^5.4.3"}
pytest-cov = {optional = true, version = "^2.10.0"}
pytest-xdist = {optional = true, version = "^1.32.0"}
python = "^3.8"
tox = {optional = true, version = "^3.16.1"}

[tool.poetry.extras]
# line1
# line2
# line3
develop = "..."
testing = "..."

[tool.poetry.scripts]
version = "..."

```

### PR DESCRIPTION
**Pull request by jonathangreen**
This PR resolves #11 and adds support to keep comments above a particular item in the toml attached to that item. To support this goal a number of changes were made:

- Add new flags for CLI: `--no-footer`, `--no-end-of-line`, `--no-inline`, `--spaces-before-comment`.
- Update documentation in the README file to reflect new comment handling.
- Add new tests
- Refactor tomlsort class to support the new comment options.

### CODE REVIEW

**Comment by jonathangreen** [comment]
@pappasam I'd love to see this get merged, but I realize its a pretty major change to the logic of `tomlsort`, let me know if there is anything I can do to help you review, or to make it easier to merge. 

Also thank you so much 🙏🏻 for creating `toml-sort`. I use it in all of my projects to keep the `pyproject.toml` nice and sorted!

**Comment by jonathangreen** [comment]
@pappasam CI should pass now, missed an import issue when I rebased my branch onto main before pushing this PR

**Comment by pappasam** [comment]
Just tested it out locally. I love the functionality, code looks great, and thanks a ton for adding all the tests!

My main issue is with the choice of naming for the CLI options / documentation

1. While there's an argument to be made in favor of changing how I discuss comments, up until now, I've always referred what you call "end of line comments" as "inline comments". See: https://github.com/pappasam/toml-sort#motivation and https://learn.microsoft.com/en-us/dotnet/visual-basic/programming-guide/program-structure/comments-in-code and https://qr.ae/prnKmx
2. Now that we have multiple comment-related CLI options, I suggest that we standardize the CLI options about comments to include the word `comments` in each flag.

Recommended new names / flags (relevant for docs as well):

```text
--no-comments  # Remove all comments. Implies no header, footer, inline, or pre-line comments.
--no-header-comments # Remove a document's leading comments.
--no-footer-comments # Remove a document's trailing comments.
--no-inline-comments # Remove all comments that are in the same line as non-comment code.
--no-pre-line-comments # Remove all full-line continuous comment groups (1 or more) whose final line directly precedes a non-comment line.
```

We can keep the `--no-header` option for now, but make it deprecated and subject to removal whenever we reach `1.0`.

I'm happy to merge this now if you'd like to handle the public API changes in a separate PR, but I won't create a release until we've a got a public API we can be happy with!

**Comment by pappasam** [comment]
@jonathangreen see comments above, thanks again for this PR. This is an incredible step forward!

**Comment by jonathangreen** [comment]
@pappasam I renamed the flags as you suggested. The only update I made to your suggestions was to use `--no-block-comments` instead of `--no-pre-line-comments`.

**Review by pappasam — APPROVED** [review]
Looks great!

**Pull request merged**
